module.exports = [
['RET_OK', {'zh': "操作成功", 'tw': "操作成功"}],
['RET_NotEnoughGold', {'zh': "金币数量不足", 'tw': "金幣數量不足"}],
//'RET_NotEnoughDiamond',
//'RET_NotEnoughEnergy',
//'RET_RoleClassNotMatch',
//'RET_RoleLevelNotMatch',
//'RET_PlayerNotExisit',
//'RET_ItemNotExist',
//'RET_InventoryFull',
//'RET_InsufficientEquipXp',
//'RET_NoEquip',
//'RET_NoEnhanceStone',
//'RET_EquipCantUpgrade',
//'RET_Unknown',
//'RET_PlayerInfoError',
//'RET_NotEnoughItem',
//'RET_TooMuchChat',
//'RET_ServerError',
//'RET_FriendListFull',
//'RET_OtherFriendListFull',
//'RET_ExceedMaxEnhanceLevel',
//'RET_SyncError',
//'RET_EnhanceFailed',
//'RET_DungeonNotExist',
//'RET_StageIsLocked',
//'RET_AppVersionNotMatch',
//'RET_ResourceVersionNotMatch',
//'RET_AccountHaveNoHero',
//'RET_WrongAccountID',
//'RET_InvalidName',
//'RET_PlayerNotExists',
//'RET_NameTaken',
//'RET_NoKey',
//'RET_CantInvite',
//'RET_Issue33',
//'RET_LoginFailed',
//'RET_HireFriendFailed',
//'RET_RequireMercenaryFailed',
//'RET_Issue37',
//'RET_Issue38',
//'RET_VipLevelIsLow',
//'RET_SoldOut',
//'RET_Issue41',
//'RET_LoginByAnotherDevice',
//'RET_NewVersionArrived',
//'RET_SessionOutOfDate',
//'RET_NeedTeammate',
//'RET_NeedReceipt',
//'RET_InsufficientIngredient',
//'RET_InvalidPaymentInfo',
//'RET_SweepPowerNotEnough',
//'RET_NotEnoughTimes',
//'RET_CantReceivePkAward',
//'RET_RewardAlreadyReceived',
//'RET_QuestNotExists',
//'RET_QuestNotAccepted',
//'RET_QuestNotCompleted',
//'RET_QuestCompleted',
//'RET_UseItemFailed',
//'RET_TargetNotExists',
//'RET_EquipedItemCannotBeSold',
//'RET_ItemSoldFailed',
//'RET_ClaimCostFailed',
//'RET_FriendNotExists',
//'RET_GetLeaderboardInfoFailed',
//'RET_ShopVersionNotMatch',
//'RET_NoParameter',
//'RET_SameMessageExist',
//'RET_ReviveLimit',
//'RET_EnergyLimit',
//'RET_RedeemFailed',
];


//ErrorMsgs = [
//    "宝石数量不足",
//    "精力值不足",
//    "角色职业不符合要求",
//    "角色等级不符合要求",//5
//    "玩家不存在",
//    "道具不存在",
//    "背包已满",
//    "装备熟练度不足",
//    "缺少装备",//10
//    "缺少强化宝石",
//    "装备无法再次升级",
//    "玩家数据有误",
//    "道具数量不足",
//    "聊天信息发送过于频繁，请稍等片刻",//15
//    "服务器状态异常，请稍后再试",
//    "你的好友列表已经满了",
//    "对方的好友列表已经满了",
//    "这个属性不能再强化了",
//    "与服务器数据同步出错，请重新登陆",//20
//    "强化失败",
//    "副本不存在",
//    "关卡尚未解锁",
//    "程序版本不匹配",
//    "资源版本不匹配",//25
//    "需要创建角色",
//    "错误的登录信息",
//    "不允许的名字",
//    "角色不存在",
//    "名字已被占用",//30
//    "没有匹配的钥匙",
//    "无法添加对方为好友",
//    "错误:33",
//    "登录失败",
//    "雇佣队友失败",//35
//    "获取队友列表失败",
//    "错误:37",
//    "错误:38",
//    "VIP等级不足",
//    "物品已经售完",//40
//    "错误:41",
//    "从另外一个设备登录",
//    "有新版本更新，请重新登录",
//    "与服务器断开连接",
//    "Need Teammate",//45
//    "缺少配方",
//    "缺少材料",
//    "付费信息错误，请联系工作人员",
//    "战斗力不足",
//    "挑战次数以用尽",//50
//    "无法领取PK奖励",
//    "奖励已领取",
//    "任务不存在",
//    "任务未领取",
//    "任务未完成",//55
//    "任务已完成",
//    "使用物品失败",
//    "目标不存在",
//    "已装备的道具无法出售",
//    "道具出售失败",//60
//    "获取材料失败",
//    "好友不存在",
//    "获取排名信息失败",
//    "商店版本不匹配",
//    "参数不正确",
//    "you have already sent this message",
//    "Revive Limit ",
//];
//
//};
